INCLUDEPATH = /home/lyj238/Downloads/cmurphi5.4.9/include
SRCPATH = /home/lyj238/Downloads/cmurphi5.4.9/src/

CXX = g++

CFLAGS = 

# optimization
OFLAGS = -ggdb
#OFLAGS = -O2

#Murphi options
MURPHIOPTS = -b -c

queen: queen.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o queen queen.cpp -I${INCLUDEPATH} -lm


queen.cpp: queen.m
	${SRCPATH}mu ${MURPHIOPTS} queen.m

genMutualEx: genMutualEx.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o genMutualEx genMutualEx.cpp -I${INCLUDEPATH} -lm


genMutualEx.cpp: genMutualEx.m
	${SRCPATH}mu ${MURPHIOPTS} genMutualEx.m

queen4: queen4.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o queen4 queen4.cpp -I${INCLUDEPATH} -lm


queen4.cpp: queen4.m
	${SRCPATH}mu ${MURPHIOPTS} queen4.m

flash_data_cubn: flash_data_cubn.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o flash_data_cubn flash_data_cubn.cpp -I${INCLUDEPATH} -lm


flash_data_cubn.cpp: flash_data_cubn.m
	${SRCPATH}mu ${MURPHIOPTS} flash_data_cubn.m

flashNew: flashNew.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o flashNew flashNew.cpp -I${INCLUDEPATH} -lm


flashNew.cpp: flashNew.m
	${SRCPATH}mu ${MURPHIOPTS} flashNew.m

cmp_lemma: cmp_lemma.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o cmp_lemma cmp_lemma.cpp -I${INCLUDEPATH} -lm


cmp_lemma.cpp: cmp_lemma.m
	${SRCPATH}mu ${MURPHIOPTS} cmp_lemma.m

german3n: german3n.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o german3n german3n.cpp -I${INCLUDEPATH} -lm


german3n.cpp: german3n.m
	${SRCPATH}mu ${MURPHIOPTS} german3n.m

flash: flash.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o flash flash.cpp -I${INCLUDEPATH} -lm


flash.cpp: flash.m
	${SRCPATH}mu ${MURPHIOPTS} flash.m

mutualExAbs: mutualExAbs.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o mutualExAbs mutualExAbs.cpp -I${INCLUDEPATH} -lm


mutualExAbs.cpp: mutualExAbs.m
	${SRCPATH}mu ${MURPHIOPTS} mutualExAbs.m

flashChou: flashChou.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o flashChou flashChou.cpp -I${INCLUDEPATH} -lm


flashChou.cpp: flashChou.m
	${SRCPATH}mu ${MURPHIOPTS} flashChou.m

german2004ModMem: german2004ModMem.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o german2004ModMem german2004ModMem.cpp -I${INCLUDEPATH} -lm
	
german2004ModMem.cpp: german2004ModMem.m
	${SRCPATH}mu ${MURPHIOPTS} german2004ModMem.m

german2004Lvyi: german2004Lvyi.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o german2004Lvyi german2004Lvyi.cpp -I${INCLUDEPATH} -lm


german2004Lvyi.cpp: german2004Lvyi.m
	${SRCPATH}mu ${MURPHIOPTS} german2004Lvyi.m

german2004: german2004.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o german2004 german2004.cpp -I${INCLUDEPATH} -lm


german2004.cpp: german2004.m
	${SRCPATH}mu ${MURPHIOPTS} german2004.m


german2004Lyj: german2004Lyj.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o german2004Lyj german2004Lyj.cpp -I${INCLUDEPATH} -lm


german2004Lyj.cpp: german2004Lyj.m
	${SRCPATH}mu ${MURPHIOPTS} german2004Lyj.m

mutualExOnI: mutualExOnI.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o mutualExOnI mutualExOnI.cpp -I${INCLUDEPATH} -lm


mutualExOnI.cpp: mutualExOnI.m
	${SRCPATH}mu ${MURPHIOPTS} mutualExOnI.m

mutualEx: mutualEx.cpp 
	${CXX} ${CFLAGS} ${OFLAGS} -o mutualEx mutualEx.cpp -I${INCLUDEPATH} -g

mutualExG: mutualEx.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o mutualEx mutualEx.cpp -I${INCLUDEPATH} -g
	
mutualEx.cpp: mutualEx.m
	${SRCPATH}mu ${MURPHIOPTS} mutualEx.m
	
mutualExFsm: mutualExFsm.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o mutualExFsm mutualExFsm.cpp -I${INCLUDEPATH} -lm

 
mutualExFsm.cpp: mutualExFsm.m
	${SRCPATH}mu ${MURPHIOPTS} mutualExFsm.m
	
gcd_2: gcd_2.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o gcd_2 gcd_2.cpp -I${INCLUDEPATH} -g
	
gcd_2.cpp: gcd_2.m
	${SRCPATH}mu ${MURPHIOPTS} gcd_2.m
	
mutualExCount1: mutualExCount1.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o mutualExCount1 mutualExCount1.cpp -I${INCLUDEPATH} -g
	
mutualExCount1.cpp: mutualExCount1.m
	${SRCPATH}mu ${MURPHIOPTS} mutualExCount1.m	
	
g2kAbs: g2kAbs.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o g2kAbs g2kAbs.cpp -I${INCLUDEPATH} -g
	
g2kAbs.cpp: g2kAbs.m
	${SRCPATH}mu ${MURPHIOPTS} g2kAbs.m		
	
g2kAbs2: g2kAbs2.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o g2kAbs2 g2kAbs2.cpp -I${INCLUDEPATH} -g
	
g2kAbs2.cpp: g2kAbs2.m
	${SRCPATH}mu ${MURPHIOPTS} g2kAbs2.m			

g2k: g2k.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o g2k g2k.cpp -I${INCLUDEPATH} -g
	
g2k.cpp: g2k.m
	${SRCPATH}mu ${MURPHIOPTS} g2k.m
	
ic3: ic3.cpp
	${CXX} ${CFLAGS} ${OFLAGS} -o ic3 ic3.cpp -I${INCLUDEPATH} -g
	
ic3.cpp: ic3.m
	${SRCPATH}mu ${MURPHIOPTS} ic3.m	
clean:
	rm -f *.cpp
